<?php
/**
 * Страница "Форма редактирования расширения".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Editing a module extension</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/edit.png' ?>" />
    </div>
    <p>The form appears after selecting the <b>"Edit"</b> item from the context menu of the selected plugin record.</p>
    <p>For each tab corresponding to a specific language, the corresponding form fields are filled in.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Module extension name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> Module extension description;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span><b>Enabled.</b> Indicates whether the module extension is currently capable of accepting and processing requests.</li>
    </ul>
</article>