<?php
/**
 * Страница "Список расширений модулей".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>List of module extensions</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list of module extensions is dynamically generated based on the active filter: either installed extensions, uninstalled extensions, or both categories are displayed.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Name.</b> Module extension name, description, and version;</li>
        <li><b>Module name.</b> The module to which this extension belongs;</li>
        <li><b>Identifier.</b> Unique identifier of the module extension;</li>
        <li><b>Path.</b> Local path to the installed module extension;</li>
        <li><b>Route.</b> Module extension invocation route (a rule linking a URL to a module extension handler);</li>
        <li><b>Author.</b> Module extension author;</li>
        <li><b>Version.</b> Module extension version;</li>
        <li><b>Enabled.</b> Indicates whether the module extension is currently capable of accepting and processing requests;</li>
        <li><b>Visible.</b> Visibility of the module extension in the Control Panel or on the website;</li>
        <li><b>Status.</b> Module extension status: installed, not installed, error, unknown.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-install.svg' ?>" /> <b>Install.</b> Opens the form to install the selected module extension from the list;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-uninstall.svg' ?>" /> <b>Uninstall.</b> Completely removes the installed module extension;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Delete.</b> Removes the downloaded module extension package;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-unmount.svg' ?>" /> <b>Unmount.</b> Removes (uninstalls) an installed module extension without deleting it from the repository;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-download.svg' ?>" /> <b>Download.</b> Downloads the module extension package corresponding to the item selected in the list;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-upload.svg' ?>" /> <b>Upload.</b> Uploads the module extension package file for subsequent installation;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Edit.</b> Opens the form for editing the module extension;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Select.</b> Selects or deselects module extensions in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of module extensions;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-update-config.svg' ?>" /> <b>Refresh.</b> Updates the configuration of installed module extensions. Used when changes are made to the configuration files of module extensions or the application;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the navigation panel to display information about the module extension;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Show / Hide.</b> Shows or hides columns that are hidden by default;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Opens the reference information window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Opens the form for searching module extensions in the list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Filter.</b> Filters the list of module extensions based on their installation status: displays either installed or uninstalled module extensions (depending on the selected criterion);</li>
    </ul>
</article>