<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Module extension manager</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The manager performs: installation, removal and dismantling of web application module extensions.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">List of module extensions</a></li>
        <li><a href="<?= $url('edit') ?>">Editing a module extension</a></li>
        <li><a href="<?= $url('install') ?>">Installing a module extension</a></li>
    </ul>
</article>